/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reto5.view;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import reto5.util.CargaReporte;
import rojeru_san.rsprogress.RSProgressBar;



/**
 *
 * @author Windows 10
 */
public class CargaLoader extends javax.swing.JFrame {
    /**
     * Creates new form Informes
     */
    public CargaLoader() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.progressBar.setValue(0);
        startThead();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.rspanel.RSPanelShadow();
        panel1 = new necesario.Panel();
        rSPanelCircleBorder1 = new rojeru_san.rspanel.RSPanelCircleBorder();
        rSPanelCircleBorder2 = new rojeru_san.rspanel.RSPanelCircleBorder();
        jLabel1 = new javax.swing.JLabel();
        rSPanelImage3 = new rojeru_san.rspanel.RSPanelImage();
        panel2 = new necesario.Panel();
        rSPanelImage2 = new rojeru_san.rspanel.RSPanelImage();
        rSPanelImage5 = new rojeru_san.rspanel.RSPanelImage();
        rSTextField1 = new rojeru_san.rsfield.RSTextField();
        progressBar = new rojeru_san.rsprogress.RSProgressBar();
        rSLabelImage1 = new rojeru_san.rslabel.RSLabelImage();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        rSPanelShadow1.setBackground(new java.awt.Color(255, 255, 255));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setColorBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelCircleBorder1.setColorBorde(new java.awt.Color(0, 0, 0));

        rSPanelCircleBorder2.setForeground(new java.awt.Color(0, 0, 0));
        rSPanelCircleBorder2.setColorBorde(new java.awt.Color(0, 112, 192));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RETO #5 ");

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/reto5/view/astronautas-01.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rSPanelCircleBorder2Layout = new javax.swing.GroupLayout(rSPanelCircleBorder2);
        rSPanelCircleBorder2.setLayout(rSPanelCircleBorder2Layout);
        rSPanelCircleBorder2Layout.setHorizontalGroup(
            rSPanelCircleBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelCircleBorder2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(rSPanelCircleBorder2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        rSPanelCircleBorder2Layout.setVerticalGroup(
            rSPanelCircleBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelCircleBorder2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rSPanelCircleBorder1Layout = new javax.swing.GroupLayout(rSPanelCircleBorder1);
        rSPanelCircleBorder1.setLayout(rSPanelCircleBorder1Layout);
        rSPanelCircleBorder1Layout.setHorizontalGroup(
            rSPanelCircleBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelCircleBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelCircleBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelCircleBorder1Layout.setVerticalGroup(
            rSPanelCircleBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelCircleBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelCircleBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(rSPanelCircleBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 320, 320));
        rSPanelCircleBorder1.getAccessibleContext().setAccessibleDescription("");

        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/reto5/view/astronautas-07.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        rSPanelImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/reto5/view/astronautas_nave.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage5Layout = new javax.swing.GroupLayout(rSPanelImage5);
        rSPanelImage5.setLayout(rSPanelImage5Layout);
        rSPanelImage5Layout.setHorizontalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        rSPanelImage5Layout.setVerticalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(rSPanelImage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, -1, 240));

        rSTextField1.setForeground(new java.awt.Color(153, 153, 153));
        rSTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rSTextField1.setText("Cargando Los Reportes, Espere un momento...");
        rSTextField1.setToolTipText("");
        rSTextField1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        rSTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextField1ActionPerformed(evt);
            }
        });
        panel1.add(rSTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 975, -1));

        progressBar.setValue(0);
        panel1.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 520, 30));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon("D:\\Windows 10\\Escritorio\\logo-login12.png")); // NOI18N
        panel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 370, 350, 120));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/reto5/view/Captura de pantalla 2022-08-03 203221.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        panel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 240, 140));

        rSPanelShadow1.add(panel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextField1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private necesario.Panel panel1;
    private necesario.Panel panel2;
    private rojeru_san.rsprogress.RSProgressBar progressBar;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage1;
    private rojeru_san.rspanel.RSPanelCircleBorder rSPanelCircleBorder1;
    private rojeru_san.rspanel.RSPanelCircleBorder rSPanelCircleBorder2;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage2;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage3;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage5;
    private rojeru_san.rspanel.RSPanelShadow rSPanelShadow1;
    private rojeru_san.rsfield.RSTextField rSTextField1;
    // End of variables declaration//GEN-END:variables

CargaReporte hilo;
    public RSProgressBar getProgress(){
        return this.progressBar;
    }
    
    public void setProgress(RSProgressBar progress){
    this.progressBar = progress;
    }
    
    public void startThead(){
        hilo = new CargaReporte(getProgress(), this);
        hilo.start();
        hilo = null;
    }
}

